"""kaizen-doctor: the diagnostic of last resort.

Every scenario here is a project shape that is broken in one specific way, plus
the healthy case. The checks that matter most are the ones proving doctor does
**not** cry wolf: an unfamiliar settings key is `info`, a genuinely new hook event
is `info`, and a clean project produces no findings at all.

A doctor that reports problems on a healthy project is worse than no doctor,
because the first false alarm is the last one anyone reads.
"""

import json
import os
import shutil
import subprocess
import sys
import tempfile

import kzparse as P

DOCTOR = os.path.join(P.PLUGIN_ROOT, "bin", "kaizen-doctor")
COMPAT = os.path.join(P.PLUGIN_ROOT, "compat", "claude-code.json")


def run(r):
    if not r.check(os.path.isfile(DOCTOR), "kaizen-doctor exists"):
        return
    r.check(os.access(DOCTOR, os.X_OK), "kaizen-doctor is executable")

    _check_registry(r)
    _check_healthy_project(r)
    _check_broken_settings(r)
    _check_missing_hook_script(r)
    _check_interpreter_hooks(r)
    _check_hook_event_typo(r)
    _check_unknown_key_is_info(r)
    _check_leftover_marker(r)
    _check_gitignored_lock(r)
    _check_no_config(r)
    _check_skill_contract(r)


# ---------------------------------------------------------------- registry ---


def _check_registry(r):
    if not r.check(os.path.isfile(COMPAT), "the compat registry exists"):
        return
    try:
        registry = P.read_json(COMPAT)
        r.ok("the compat registry is valid JSON")
    except ValueError as exc:
        r.fail("the compat registry is valid JSON", exc)
        return

    import re
    r.check(
        re.match(r"^\d{4}\.\d{2}$", registry.get("compat_version", "")) is not None,
        "the registry uses calendar versioning (%s)" % registry.get("compat_version"),
        "the platform moves faster than kaizen releases; freshness is the point",
    )
    for key in ("settings_keys_known", "permissions_keys_known",
                "permissions_default_modes", "hook_events_known",
                "settings_keys_deprecated", "hook_events_deprecated",
                "external_tools", "verified_against"):
        r.check(key in registry, "the registry declares `%s`" % key)

    # Every hook event kaizen itself wires must be one the registry knows, or
    # doctor would flag kaizen's own output.
    events = set(registry.get("hook_events_known", []))
    hooks_json = os.path.join(P.HOOKS_DIR, "hooks.json")
    if os.path.isfile(hooks_json):
        for event in P.read_json(hooks_json).get("hooks", {}):
            if event.startswith("_"):
                continue
            r.check(
                event in events,
                "the registry knows the `%s` event kaizen wires" % event,
            )
    for preset in P.preset_dirs():
        path = os.path.join(P.TEMPLATES_DIR, preset, ".claude", "settings.json")
        if not os.path.isfile(path):
            continue
        settings = P.read_json(path)
        for event in (settings.get("hooks") or {}):
            r.check(
                event in events,
                "the registry knows `%s`, wired by the %s preset" % (event, preset),
            )
        known_keys = set(registry.get("settings_keys_known", []))
        for key in settings:
            if key.startswith("_") or key == "$schema":
                continue
            r.check(
                key in known_keys,
                "the registry knows `%s`, generated by the %s preset" % (key, preset),
                "otherwise doctor reports kaizen's own output as unrecognised",
            )


# --------------------------------------------------------------- scenarios ---


class _project(object):
    """A temp git repo, optionally seeded with files."""

    def __init__(self, files=None, git=True):
        self.files = files or {}
        self.git = git

    def __enter__(self):
        self.path = tempfile.mkdtemp(prefix="kaizen-doctor-")
        for rel, content in self.files.items():
            full = os.path.join(self.path, rel)
            directory = os.path.dirname(full)
            if directory and not os.path.isdir(directory):
                os.makedirs(directory)
            with open(full, "w", encoding="utf-8") as fh:
                fh.write(content)
        if self.git:
            subprocess.run(["git", "init", "-q", "-b", "main"], cwd=self.path,
                           capture_output=True)
        return self.path

    def __exit__(self, *exc):
        shutil.rmtree(self.path, ignore_errors=True)
        return False


def _diagnose(r, project, label):
    env = dict(os.environ)
    env["CLAUDE_PROJECT_DIR"] = project
    proc = subprocess.run([sys.executable, DOCTOR], capture_output=True, text=True,
                          env=env, cwd=project, timeout=60)
    try:
        return json.loads(proc.stdout), proc
    except ValueError as exc:
        r.fail("doctor emits valid JSON (%s)" % label,
               "%s\n%s\n%s" % (exc, proc.stdout[:300], proc.stderr[:300]))
        return None, proc


def _summaries(report, severity=None):
    return [f["summary"] for f in report["findings"]
            if severity is None or f["severity"] == severity]


HEALTHY_SETTINGS = json.dumps({
    "permissions": {"allow": ["Bash(npm test *)"], "deny": ["Bash(sudo *)"],
                    "defaultMode": "default"},
    "includeCoAuthoredBy": True,
}, indent=2)


def _check_healthy_project(r):
    """The most important scenario: nothing wrong, so nothing reported."""
    files = {
        "CLAUDE.md": "# Conventions\n\n- Named exports only.\n",
        ".claude/settings.json": HEALTHY_SETTINGS,
        ".claude/rules/testing.md": "---\npaths: [\"**/*.test.ts\"]\n---\n\n# Testing\n",
        ".claude/agents/code-reviewer.md": "---\nname: code-reviewer\ndescription: Reviews code thoroughly on request.\ntools: Read, Grep\n---\n\nbody\n",
    }
    with _project(files) as project:
        report, proc = _diagnose(r, project, "healthy")
        if report is None:
            return
        problems = _summaries(report, "problem")
        r.check(
            not problems,
            "a healthy project reports no problems",
            "the first false alarm is the last one anyone reads:\n%s"
            % "\n".join(problems),
        )
        r.check(
            proc.returncode == 0,
            "doctor exits 0 on a healthy project",
            "exit %d" % proc.returncode,
        )
        # A missing lock is a warning, not a problem — most projects have none.
        r.check(
            any("lock" in s for s in _summaries(report, "warning")),
            "a project with no lock gets a warning, not a problem",
        )


def _check_broken_settings(r):
    with _project({".claude/settings.json": "{ this is not json"}) as project:
        report, proc = _diagnose(r, project, "unparseable settings")
        if report is None:
            return
        r.check(
            any("not valid JSON" in s for s in _summaries(report, "problem")),
            "unparseable settings.json is a problem",
        )
        r.check(proc.returncode == 1, "doctor exits 1 when something is broken")


def _check_missing_hook_script(r):
    settings = json.dumps({
        "hooks": {"SessionStart": [{"hooks": [
            {"type": "command",
             "command": "${CLAUDE_PROJECT_DIR}/.claude/hooks/gone.sh"}]}]},
    })
    with _project({".claude/settings.json": settings}) as project:
        report, _ = _diagnose(r, project, "missing hook script")
        if report is None:
            return
        r.check(
            any("does not exist" in s for s in _summaries(report, "problem")),
            "a hook pointing at a missing script is a problem",
            "Claude Code errors on every event until it is fixed",
        )

    # ...and an existing but non-executable one.
    with _project({".claude/settings.json": settings,
                   ".claude/hooks/gone.sh": "#!/usr/bin/env bash\nexit 0\n"}) as project:
        os.chmod(os.path.join(project, ".claude/hooks/gone.sh"), 0o644)
        report, _ = _diagnose(r, project, "non-executable hook")
        if report is None:
            return
        r.check(
            any("not executable" in s for s in _summaries(report, "problem")),
            "a hook script without the exec bit is a problem",
        )


def _check_interpreter_hooks(r):
    """`node script.mjs` is a normal hook. Doctor used to call `node` a missing file.

    Found by running doctor against a real project. The first token of a hook
    command is not necessarily a path — it is often an interpreter, and the thing
    that actually goes missing is its script argument.
    """
    def settings_for(command):
        return json.dumps({"hooks": {"PostToolUse": [
            {"matcher": "Edit", "hooks": [{"type": "command", "command": command}]}]}})

    # Interpreter on PATH + a script that exists → nothing to report.
    files = {
        ".claude/settings.json": settings_for("node .claude/hooks/reminder.mjs"),
        ".claude/hooks/reminder.mjs": "process.exit(0);\n",
    }
    with _project(files) as project:
        report, _ = _diagnose(r, project, "interpreter + existing script")
        if report is None:
            return
        r.check(
            not _summaries(report, "problem"),
            "`node script.mjs` with the script present reports nothing",
            "FALSE POSITIVE:\n%s" % "\n".join(_summaries(report, "problem")),
        )

    # Interpreter on PATH, script missing → the script is the finding.
    with _project({".claude/settings.json":
                   settings_for("node .claude/hooks/gone.mjs")}) as project:
        report, _ = _diagnose(r, project, "interpreter + missing script")
        if report is None:
            return
        r.check(
            any("runs a script that does not exist" in s
                for s in _summaries(report, "problem")),
            "a missing interpreter script is reported as the missing script",
            "\n".join(_summaries(report)),
        )
        r.check(
            not any("`node`" in (f.get("detail") or "") and "not exist" in f["summary"]
                    for f in report["findings"]),
            "the interpreter itself is never reported as a missing file",
        )

    # An interpreter that is genuinely absent → say so about the interpreter.
    with _project({".claude/settings.json":
                   settings_for("definitely-not-installed-xyz run.sh")}) as project:
        report, _ = _diagnose(r, project, "missing interpreter")
        if report is None:
            return
        r.check(
            any("is not installed" in s for s in _summaries(report, "problem")),
            "a hook needing an uninstalled program says which program",
        )

    # A script hook without an interpreter still works the old way.
    with _project({".claude/settings.json":
                   settings_for("${CLAUDE_PROJECT_DIR}/.claude/hooks/direct.sh")}) as project:
        report, _ = _diagnose(r, project, "direct script hook")
        if report is None:
            return
        r.check(
            any("does not exist" in s for s in _summaries(report, "problem")),
            "a direct script path that is missing is still a problem",
        )


def _check_hook_event_typo(r):
    """A misspelled event never fires and never errors — the worst failure mode."""
    settings = json.dumps({
        "hooks": {"SesionStart": [{"hooks": [
            {"type": "command", "command": "/bin/echo"}]}]},
    })
    with _project({".claude/settings.json": settings}) as project:
        report, _ = _diagnose(r, project, "typo'd event")
        if report is None:
            return
        r.check(
            any("misspelling of `SessionStart`" in s
                for s in _summaries(report, "problem")),
            "a misspelled hook event is caught as a typo, not shrugged off",
            "\n".join(_summaries(report)),
        )

    # A plausibly-new event name must NOT be called a typo.
    settings = json.dumps({
        "hooks": {"SubagentReasoningDelta": [{"hooks": [
            {"type": "command", "command": "/bin/echo"}]}]},
    })
    with _project({".claude/settings.json": settings}) as project:
        report, _ = _diagnose(r, project, "unknown event")
        if report is None:
            return
        r.check(
            any("does not recognise the hook event" in s
                for s in _summaries(report, "info")),
            "an unfamiliar hook event is info, not a problem",
            "the registry cannot know events added after it was written",
        )
        r.check(
            not any("SubagentReasoningDelta" in s
                    for s in _summaries(report, "problem")),
            "an unfamiliar hook event is never reported as broken",
        )


def _check_unknown_key_is_info(r):
    settings = json.dumps({"someKeyFromTheFuture": True,
                           "permissions": {"defaultMode": "default"}})
    with _project({".claude/settings.json": settings}) as project:
        report, proc = _diagnose(r, project, "unknown key")
        if report is None:
            return
        r.check(
            any("someKeyFromTheFuture" in s for s in _summaries(report, "info")),
            "an unrecognised settings key is info",
            "kaizen not knowing a key is a statement about kaizen",
        )
        r.check(
            not any("someKeyFromTheFuture" in s for s in _summaries(report, "problem")),
            "an unrecognised settings key is never a problem",
        )
        r.check(
            proc.returncode == 0,
            "info findings alone do not make doctor exit non-zero",
        )

    # An invalid defaultMode IS worth a warning, because the set is closed.
    settings = json.dumps({"permissions": {"defaultMode": "yolo"}})
    with _project({".claude/settings.json": settings}) as project:
        report, _ = _diagnose(r, project, "bad defaultMode")
        if report is None:
            return
        r.check(
            any("defaultMode" in s for s in _summaries(report, "warning")),
            "an unknown defaultMode is flagged",
        )


def _check_leftover_marker(r):
    files = {
        "CLAUDE.md": "# Conventions\n\nProject: {{PROJECT_NAME}}\n",
        ".claude/settings.json": HEALTHY_SETTINGS,
    }
    with _project(files) as project:
        report, _ = _diagnose(r, project, "leftover marker")
        if report is None:
            return
        r.check(
            any("{{PROJECT_NAME}}" in s for s in _summaries(report, "problem")),
            "an unsubstituted template marker in CLAUDE.md is a problem",
            "the user is reading a literal placeholder every session",
        )

    files["CLAUDE.md"] = "# Conventions\n\n<!-- KAIZEN_STANDARDS:claude_md.conventions -->\n"
    with _project(files) as project:
        report, _ = _diagnose(r, project, "leftover standards marker")
        if report is None:
            return
        r.check(
            any("KAIZEN_STANDARDS" in s for s in _summaries(report, "problem")),
            "an unfilled standards marker is a problem",
        )


def _check_gitignored_lock(r):
    lock = json.dumps({"files": [{"path": "CLAUDE.md", "sha256": "x"}],
                       "placeholders": {"PACKAGE_MANAGER": "npm"}})
    files = {
        "CLAUDE.md": "# Conventions\n",
        ".claude/settings.json": HEALTHY_SETTINGS,
        ".claude/kaizen/lock.json": lock,
        ".claude/kaizen/baseline/CLAUDE.md": "# Conventions\n",
        ".gitignore": ".claude/kaizen/\n",
    }
    with _project(files) as project:
        report, _ = _diagnose(r, project, "gitignored lock")
        if report is None:
            return
        r.check(
            any("gitignored" in s for s in _summaries(report, "problem")),
            "a gitignored lock file is a problem",
            "a teammate cloning the repo cannot upgrade safely",
        )

    files[".gitignore"] = (".claude/kaizen/*\n!.claude/kaizen/lock.json\n"
                           "!.claude/kaizen/baseline/\n")
    with _project(files) as project:
        report, _ = _diagnose(r, project, "correctly un-ignored lock")
        if report is None:
            return
        r.check(
            not any("gitignored" in s for s in _summaries(report, "problem")),
            "the negated .gitignore form is accepted",
            "this is exactly what kaizen's own template writes",
        )


def _check_no_config(r):
    with _project({"README.md": "# hello\n"}) as project:
        report, proc = _diagnose(r, project, "no config at all")
        if report is None:
            return
        r.check(
            not _summaries(report, "problem"),
            "a project kaizen has never touched reports no problems",
            "not being set up is not a fault:\n%s" % "\n".join(_summaries(report, "problem")),
        )
        r.check(
            proc.returncode == 0,
            "doctor exits 0 on a project with no kaizen config",
        )


def _check_skill_contract(r):
    """The skill must delegate to the script and preserve its severities."""
    path = os.path.join(P.SKILLS_DIR, "doctor", "SKILL.md")
    if not r.check(os.path.isfile(path), "the doctor skill exists"):
        return
    body = P.read(path)
    r.check("Bash(kaizen-doctor" in body, "the doctor skill may run kaizen-doctor")
    r.check("kaizen-doctor" in body, "the doctor skill delegates to the script")
    for severity in ("problem", "warning", "info"):
        r.check(
            severity in body,
            "the doctor skill documents the `%s` severity" % severity,
        )
    r.check(
        "NEVER present an `info` finding as a problem" in body,
        "the doctor skill is told not to escalate an info finding",
        "reporting an unfamiliar key as invalid makes kaizen wrong the day the "
        "platform ships a new one",
    )
    r.check(
        "NEVER guess a `paths:` glob" in body,
        "the doctor skill is told not to guess rule globs",
    )
