#!/usr/bin/env bash
# kaizen :: seed a project into the "already initialised by an older kaizen" state
#
#   seed-project.sh <project-dir> <fixture-name> [old-plugin-version] [old-standards-version]
#
# Builds the state /kaizen:upgrade and /kaizen:analyze expect to find, WITHOUT
# spending a live /kaizen:init: renders the config from the catalog exactly the
# way init would, records it with kaizen-lock, then adds the two things that make
# an upgrade interesting — a convention the user wrote by hand, and a generated
# file the user deleted.
#
# Deterministic and free. The live session is then spent only on the skill under
# test, which is the part that actually needs a model.

set -euo pipefail

PROJECT="${1:?need a project dir}"
FIXTURE="${2:?need a fixture name}"
OLD_PLUGIN="${3:-0.12.0}"
OLD_STANDARDS="${4:-2026.07}"

LIVE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$(dirname "$LIVE_DIR")")"
BIN="$REPO_ROOT/plugins/kaizen/bin"

export CLAUDE_PROJECT_DIR="$PROJECT"
cd "$PROJECT"

FINGERPRINT="$("$BIN/kaizen-detect")"
STACK="$(printf '%s' "$FINGERPRINT" | sed -n 's/.*"stack": "\([^"]*\)".*/\1/p')"
MATURITY="$(printf '%s' "$FINGERPRINT" | sed -n 's/.*"maturity": "\([^"]*\)".*/\1/p')"
NAME="$(printf '%s' "$FINGERPRINT" | sed -n 's/.*"project_name": "\([^"]*\)".*/\1/p')"

render() { "$BIN/kaizen-standards" render --surface "$1" --stack "$STACK" --maturity "$MATURITY" || true; }

mkdir -p .claude/rules .claude/hooks

# CLAUDE.md as init would have produced it, minus the enrichment sections that
# need a model. The rules come from the catalog, which is the part under test.
{
  printf '# Project conventions\n\n'
  printf '> Project: **%s** · Stack: %s · PM: `npm`\n' "$NAME" "$STACK"
  printf '> Generated by kaizen. Keep this under ~200 lines.\n\n'
  printf '## Commands\n\n- Install: `npm install`\n- Test: `npm run test`\n\n'
  printf '## Conventions\n\n'
  render claude_md.conventions
  printf '\n## Never do\n\n'
  render claude_md.never
  printf '\n'
} > CLAUDE.md

printf '{\n  "permissions": { "allow": ["Bash(npm test)"] }\n}\n' > .claude/settings.json
printf '#!/usr/bin/env bash\nset -euo pipefail\nexit 0\n' > .claude/hooks/session-start.sh
chmod +x .claude/hooks/session-start.sh
{
  printf -- '---\npaths: ["**/*.test.ts"]\n---\n\n# Testing rules\n\n## Conventions\n\n'
  render rules_testing.conventions
  printf '\n'
} > .claude/rules/testing.md

"$BIN/kaizen-lock" write \
  --plugin-version "$OLD_PLUGIN" --standards-version "$OLD_STANDARDS" \
  --profile standard --preset typescript-node \
  CLAUDE.md .claude/settings.json .claude/rules/testing.md .claude/hooks/session-start.sh \
  > /dev/null

# --- now make it a project someone has actually lived in --------------------

# 1. A convention the user wrote themselves. No catalog id: kaizen must never
#    judge it, never merge it away, never claim it as its own.
printf -- '- NEVER call the billing API without an idempotency key.\n' >> CLAUDE.md

# 2. A generated file the user deleted on purpose. Must stay deleted.
rm -f .claude/hooks/session-start.sh

# 3. A file kaizen never wrote. Must be untouched by anything.
printf -- '---\npaths: ["src/**"]\n---\n\n# House rules\n\nOurs, not kaizen'"'"'s.\n' \
  > .claude/rules/house-style.md

printf 'seeded %s (stack=%s maturity=%s) at plugin=%s standards=%s\n' \
  "$FIXTURE" "$STACK" "$MATURITY" "$OLD_PLUGIN" "$OLD_STANDARDS"
